---
title: "Hipótesis"
author: "Martin Santamaria"
date: "12/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(RETICULATE_PYTHON = "/Python38")
library(reticulate)
```

```{r}
set.seed(230)

flores.elegidas.40=sample(1:150,40,replace=TRUE)
muestra.iris.40.long.sepal = iris[flores.elegidas.40,]$Sepal.Length

t = t.test(muestra.iris.40.long.sepal,mu = 5.7, alternative = "greater", conf.level = 0.95)

t

t$method
t$data.name
t$statistic
t$parameter
t$p.value
t$estimate
t$conf.int
t$stderr
t$alternative
```

```{r}
binom.test(21,25,p=0.8,alternative="greater",conf.level=0.95)
```

```{r}
library(MASS)

n = 30
madres.elegidas = sample(1:189,n,replace = TRUE)
madres.fumadoras = table(birthwt[madres.elegidas,]$smoke)[1]

binom.test(madres.fumadoras, n, p = 0.30, alternative = "greater")
```

```{r}
n = 100

binom.test(53, n, p = 0.70, alternative = "less")
prop.test(53, n, p = 0.7, alternative = "less" ,conf.level = 0.95)
```

```{r}
library(TeachingDemos)

muestra = c(521,742,593,635,788,717,606,639,666,624)
n = length(muestra)
var.muestral = var(muestra)
sigma2_0 = 6400
chi2_0 = (n-1)*var.muestral/sigma2_0
alpha = 0.05

#p-valor
2*pchisq(chi2_0,df=n-1,lower.tail = FALSE)

#Intervalo de confianza
c((n-1)*var.muestral/qchisq(1-alpha/2,df=n-1),(n-1)*var.muestral/qchisq(alpha/2,df=n-1))

sigma.test(muestra,sigmasq = sigma2_0, alternative = "two.sided", conf.level = 0.95)
```

```{r}
n = 40
flores.elegidas = sample(1:150,n,replace = TRUE)
muestra.sepal.width = iris[flores.elegidas,]$Sepal.Width
sigma2_0 = 0.2
var.muestral = var(muestra.sepal.width)
chi2_0 = (n-1)*var.muestral/sigma2_0

#p-valor
pchisq(chi2_0,df=n-1)

#Intervalo de confianza
c(0,(n-1)*var.muestral/qchisq(alpha,df=n-1))

sigma.test(muestra.sepal.width,sigmasq = sigma2_0, alternative = "less", conf.level = 0.95)
```

```{r}
flores.elegidas.setosa = sample(1:50,40,replace=TRUE)
flores.elegidas.versicolor = sample(51:100,40,replace=TRUE)

muestra.setosa = iris[flores.elegidas.setosa,]
muestra.versicolor = iris[flores.elegidas.versicolor,]

t.test(muestra.setosa$Petal.Length,muestra.versicolor$Petal.Length,alternative="two.sided")
t.test(muestra.setosa$Petal.Length,muestra.versicolor$Petal.Length,alternative="two.sided")$conf.int
t.test(muestra.setosa$Petal.Length,muestra.versicolor$Petal.Length,alternative="two.sided",var.equal = TRUE)
```

```{r}
library(MASS)

n=50
madres.raza.blanca = rownames(birthwt[birthwt$race==1,])
madres.raza.negra = rownames(birthwt[birthwt$race==2,])

madres.elegidas.blanca=sample(madres.raza.blanca,n,replace=TRUE)
madres.elegidas.negra = sample(madres.raza.negra,n, replace=TRUE)
muestra.madres.raza.blanca = birthwt[madres.elegidas.blanca,]
muestra.madres.raza.negra = birthwt[madres.elegidas.negra,]

muestra.madres = rbind(muestra.madres.raza.blanca,muestra.madres.raza.negra)

(matriz.fisher=table(muestra.madres$smoke,muestra.madres$race))
(matriz.fisher = rbind(matriz.fisher[2,],matriz.fisher[1,]))

fisher.test(matriz.fisher)
```

```{r}
n.blanca = table(muestra.madres.raza.blanca$smoke)[2]
n.negra = table(muestra.madres.raza.negra$smoke)[2]

prop.test(c(n.blanca,n.negra),c(50,50))
prop.test(c(n.blanca,n.negra),c(50,50))$conf.int
```

```{r}
prop.test(c(20,25),c(50,100),conf.level = 0.95,alternative = "greater")
```

```{r}
var.test(muestra.setosa$Petal.Length,muestra.versicolor$Petal.Length)
var.test(muestra.setosa$Petal.Length,muestra.versicolor$Petal.Length)$conf.int

# No paramétrico
fligner.test(list(muestra.setosa$Petal.Length,muestra.versicolor$Petal.Length))
```

```{r}
flores.elegidas.virginica = sample(101:150,40,replace=TRUE)
muestra.virginica = iris[flores.elegidas.virginica,]

t.test(muestra.virginica$Sepal.Length,muestra.virginica$Petal.Length,alternative = "greater",paired = TRUE)
t.test(muestra.virginica$Sepal.Length,muestra.virginica$Petal.Length,paired=TRUE,alternative="greater")$conf.int
```

```{r}
library(MASS)

madres.elegidas.prop.empar = sample(1:189,30,replace=TRUE)
muestra.madres.prop.empar = birthwt[madres.elegidas.prop.empar,]

(matriz.prop.empar = table(muestra.madres.prop.empar$smoke,muestra.madres.prop.empar$ht))

matriz.prop.empar = rbind(matriz.prop.empar[2,],matriz.prop.empar[1,])
matriz.prop.empar = cbind(matriz.prop.empar[,2],matriz.prop.empar[,1])

matriz.prop.empar

mcnemar.test(matriz.prop.empar)
```

```{r}
(n=matriz.prop.empar[1,2]+matriz.prop.empar[2,1])

(exitos=matriz.prop.empar[2,1])

binom.test(exitos,n,p=0.5)
```

## En `Python`

### Proporciones

```{python}
import statsmodels.api as sm
import numpy as np
import matplotlib.pyplot as plt
import statistics as st
import pandas as pd
```

$$
\left\{
\begin{array}{ll}
H_0: & p = 0.52 \\
H_1: & p > 0.52
\end{array}
\right.
$$

```{python}
# Contrastes para la proporcion poblacional p
n = 1018
x = 570
p_null = 0.52
p_hat = x/n

print(f"{p_hat}")
```

```{python}
ht = sm.stats.proportions_ztest(x, n, p_null, alternative = 'larger')

print(f"El estadistico de contraste es {round(ht[0],3)} y su p-valor es {round(ht[1],3)}")
```

$$
\left\{
\begin{array}{ll}
H_0: & p_1 - p_2 = 0 \\
H_1: & p_1 - p_2 \neq 0
\end{array}
\right.
$$

```{python}
# Contrastes de dos muestras
n1 = 247
p1 = .37

n2 = 308
p2 = .39

population1 = np.random.binomial(1, p1, n1)
population2 = np.random.binomial(1, p2, n2)

print(population1)
print(population2)

sm.stats.ttest_ind(population1, population2)
```

```{python}
data = [80.57, 98.96, 85.28, 83.83, 69.94, 89.59, 91.09, 66.25, 91.21, 82.7 , 73.54, 81.99, 54.01, 82.89, 75.88, 98.32, 107.2 , 85.53, 79.08, 84.3 , 89.32, 86.35, 78.98, 92.26, 87.01]
```

$$
\left\{
\begin{array}{ll}
H_0: & \mu = 80 \\
H_1: & \mu > 80
\end{array}
\right.
$$

```{python}
n = len(data)
x_bar = st.mean(data)
s_tilde = st.stdev(data)

print(f"El tamanio de la muestra es {n}, la media muestral es {x_bar} y la desviacion muestral {s_tilde}")
```

```{python}
sm.stats.ztest(data, value = 80, alternative = "larger")

plt.hist(data)
plt.show()
```

$$
\left\{
\begin{array}{ll}
H_0: & \mu_1 = \mu_2 \\
H_1: & \mu_1 \neq \mu_2
\end{array}
\right.
$$

```{python}
url = "https://raw.githubusercontent.com/MartinSantaGitHub/estadistica-inferencial/master/datasets/nhanes_2015_2016.csv"

data = pd.read_csv(url)
data.head()

females = data[data["RIAGENDR"]==2]
males = data[data["RIAGENDR"]==1]

print(f"El numero de mujeres de la muestra son: {len(females)} y el numero de hombres es: {len(males)}")
```

Limpieza de los datos

```{python}
fem_bmi = females["BMXBMI"].dropna()
mal_bmi = males["BMXBMI"].dropna()

fig, axs = plt.subplots(2)
fig.suptitle('Data normally distributed')

axs[0].hist(fem_bmi)
axs[1].hist(mal_bmi, facecolor = "g")

plt.show()
```

```{python}
sm.stats.ztest(fem_bmi, mal_bmi, alternative = "two-sided")
```

